### PR TITLE
Fix internal types for TS4.9, add `module: node16`

### PR DESCRIPTION
**Pull request by ChristianMurphy**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

This includes:
- [x] TypeScript 4.9 fixes
- [x] Internal fixes TypeScript ESM resolution in Node16 mode
- [x] New conditional exports for TypeScript ESM

### CODE REVIEW

**Review by remcohaszing — APPROVED** [review]

**Comment by wooorm** [comment]
Looks like TS4.9 problems 😬

**Comment by ChristianMurphy** [comment]
D'oh, I didn't clear _node_modules_ when testing locally, was using an older TS version.
Clearing now, and looking into the TS3.9 errors.

**Comment by ChristianMurphy** [comment]
@wooorm there are four TS errors remaining which I'm not quite sure what to make of:

```
dev/lib/compile.js:528:7 - error TS2554: Expected 1 arguments, but got 0.

528       onexitlistitem()
          ~~~~~~~~~~~~~~~~

  ../micromark-util-types/index.d.ts:625:45
    625 export type Handle = (this: CompileContext, token: Token) => void;
                                                    ~~~~~~~~~~~~
    An argument for 'token' was not provided.

dev/lib/compile.js:543:5 - error TS2554: Expected 1 arguments, but got 0.

543     onexitlistitem()
        ~~~~~~~~~~~~~~~~

  ../micromark-util-types/index.d.ts:625:45
    625 export type Handle = (this: CompileContext, token: Token) => void;
                                                    ~~~~~~~~~~~~
    An argument for 'token' was not provided.

dev/lib/compile.js:554:5 - error TS2554: Expected 1 arguments, but got 0.

554     onexitlistitem()
        ~~~~~~~~~~~~~~~~

  ../micromark-util-types/index.d.ts:625:45
    625 export type Handle = (this: CompileContext, token: Token) => void;
                                                    ~~~~~~~~~~~~
    An argument for 'token' was not provided.

dev/lib/compile.js:1021:5 - error TS2554: Expected 1 arguments, but got 0.

1021     onenterhtml()
         ~~~~~~~~~~~~~

  ../micromark-util-types/index.d.ts:625:45
    625 export type Handle = (this: CompileContext, token: Token) => void;
                                                    ~~~~~~~~~~~~
    An argument for 'token' was not provided.


Found 4 errors in the same file, starting at: dev/lib/compile.js:528
```

It looks like `onexitlistitem` is/was defined as implementing `Handle`
https://github.com/micromark/micromark/blob/c0602c2453ac7c31e076512a512504426efe9dc1/packages/micromark/dev/lib/compile.js#L542-L550

and `Handle` does have a required param

https://github.com/micromark/micromark/blob/af8df6946b2653eaedd2188cb7220742e4d3e520/packages/micromark-util-types/index.js#L485

Not sure why it didn't error in previous versions.

Is this something that should be marked as `?` optional in the interface?
Or are these a different type of `Handle` than the rest that should have their own interface?

**Comment by wooorm** [comment]
Btw, I see you mention TS3.9. I thought we were at TS4+ for a while already, is this TC39 going on in your head? 😅

Re TS4.8 and lower, yeah, they took everything from `Handle` but dropped unused parameters. In 4.9 it doesn’t anymore.

I’ve been removing `Handle`s and typing things at every function instead.

**Comment by ChristianMurphy** [comment]
> Btw, I see you mention TS3.9. I thought we were at TS4+ for a while already

Yes TS4.9, sorry, typo on my part.

> I’ve been removing Handles and typing things at every function instead.

I'll look into this, thanks!

**Comment by ChristianMurphy** [comment]
Types are happy now.
However, implementation tests are not, despite the implementation not changing 😅 
I suspect some dependency drift is at play here:

```
not ok 624 should be strictly equal
  ---
    operator: equal
    expected: |-
      '<p>foo <!-- this is a --\ncomment - with hyphens --></p>\n'
    actual: |-
      '<p>foo &lt;!-- this is a --\ncomment - with hyphens --&gt;</p>\n'
    stack: |-
      Error: should be strictly equal
          at Test.assert [as _assert] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:312:48)
          at Test.bound [as _assert] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.strictEqual (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:476:7)
          at Test.bound [as equal] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.<anonymous> (file:///home/runner/work/micromark/micromark/test/commonmark.js:31:11)
          at Test.bound [as _cb] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.run (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:115:28)
          at Test.bound [as run] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test._end (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:218:5)
          at Test.bound [as _end] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
  ...
not ok 625 should be strictly equal
  ---
    operator: equal
    expected: |-
      '<p>foo <!--> foo --&gt;</p>\n<p>foo <!---> foo --&gt;</p>\n'
    actual: |-
      '<p>foo &lt;!--&gt; foo --&gt;</p>\n<p>foo &lt;!---&gt; foo --&gt;</p>\n'
    stack: |-
      Error: should be strictly equal
          at Test.assert [as _assert] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:312:48)
          at Test.bound [as _assert] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.strictEqual (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:476:7)
          at Test.bound [as equal] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.<anonymous> (file:///home/runner/work/micromark/micromark/test/commonmark.js:31:11)
          at Test.bound [as _cb] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test.run (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:115:28)
          at Test.bound [as run] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
          at Test._end (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:218:5)
          at Test.bound [as _end] (/home/runner/work/micromark/micromark/node_modules/tape/lib/test.js:95:17)
  ...
```

https://github.com/micromark/micromark/actions/runs/3970012007/jobs/6805229216#step:6:913

**Comment by wooorm** [comment]
These tests are intentional: it’s me!. A change to CM that hasn’t strictly been released:

- https://github.com/wooorm/commonmark.json/commit/d323048079ceeae7f5f5f11e1cc90f9a82c78b6b
- https://github.com/commonmark/commonmark-spec/commit/d5ddfae696c53f09fd5b6182238de716dddeb40a
- https://github.com/commonmark/commonmark-spec/commit/ea177af1066ef0eefcf2ffebc23f8bf968b69f67

**Comment by wooorm** [comment]
I’m fine with this PR here, without comments, although would be nice to get those canaries to not fail so hard 😅

**Review by wooorm — APPROVED** [review]

**Pull request merged**
